name: Test flake

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  test-flake:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          # - macos-11

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@v26

    - name: Flake metadata
      run: nix flake metadata

    - name: Flake show
      run: nix flake show

    - name: Flake check
      run: nix flake check --impure --accept-flake-config
