name: Run tests

on:
  schedule:
    - cron:  '0 1 * * 1'

  pull_request:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
  NEW_GITHUB_WORKSPACE: "/home/runner/work/geonix"

jobs:
  check-flake:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          # - macos-11

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@v26

    - name: Flake metadata
      run: nix flake metadata

    - name: Flake show
      run: nix flake show

    - name: Flake check
      run: nix flake check --impure --accept-flake-config


  test:
    strategy:
      fail-fast: false
      matrix:
        environment:
          - basic
          - basic-process
          - container-process
          - container-python
          - container-shell
          - custom-package
          - example-python-web
          - geonixcli
          - locales
          - pg_featureserv
          - pg_tileserv
          - postgres
          - python-poetry
        os:
          - ubuntu-22.04
          # - macos-11

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Low limit on unix socket path length is causing the problems with PostgreSQL shell.
    - name: Move source code on shorter path
      run: |
        mv $GITHUB_WORKSPACE $NEW_GITHUB_WORKSPACE
        mkdir -p $GITHUB_WORKSPACE

    - name: Install nix
      uses: cachix/install-nix-action@v26

    - name: Setup cachix
      uses: cachix/cachix-action@v14
      with:
        name: geonix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Run test
      run: bash ./test.sh
      working-directory: ${{ env.NEW_GITHUB_WORKSPACE }}/tests/${{ matrix.environment }}
